name: UltraHardCoreMode
main: io.github.christiangaertner.ultrahardcoremode.UltraHardCoreMode
author: DaGardnerDev
version: 1.1.1
description: SethBlings UHC-Box ported to Craftbukkit
commands:
  uhc-toogle:
    description: Toogles the UHC for the player who issued the command or attached player or 'global' flag for everyone
    usage: /<command> [option:player|global]
  uhc-heal:
    description: Removes one gold ingot and an apple from your inventory and heals you by a certain number of hearts
    usage: Requires 1 Apple and 1 Goldblock in your inventory /<command>
  uhc-list:
    description: Shows every player who is currently disabled in UHC
    usage: /<command>
  uhc-resetconfig:
    description: Resets the config to default values
    usage: /<command>
permissions:
  uhc.*:
    description: Give access to all commands
    children:
      uhc.bypass: true
      uhc.list: true
      uhc.toogle.*: true
      uhc.toogle.self: true
      uhc.toogle.remote: true
  uhc.toogle.*:
    description: Allows the user to toogle UHC on or off for both them and others
    children:
      uhc.toogle.self: true
      uhc.toogle.remote: true
  uhc.toogle.self:
    description: Allows the user to toogle UHC on or off
  uhc.toogle.remote:
    description: Allows the user to toogle UHC on or off for both them and others
  uhc.bypass:
    description: Bypasses the UHC Plugin
  uhc.denyheal:
    description: Permits the usage of the command /heal
  uhc.list:
    description: Allows to list every disabled player
  uhc.resetconfig:
    description: Allows to reset the config